In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [9]:
#속성: data.속성    method: data.method()   
arr1d = np.array([1,2,3,4,5])
print(arr1d)
arr2d = np.array([[1,2,3],[4,5,6]])
print(arr2d)
print(arr2d.shape, arr2d.ndim, arr2d.dtype)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
(2, 3) 2 int32


In [10]:
lst = [1,2,3]
arr = np.array(lst)
print(type(lst))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [14]:
arr = np.arange(10)
print(arr)
arr = np.arange(2,20,2, dtype=float)
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[ 2.  4.  6.  8. 10. 12. 14. 16. 18.]


In [28]:
zeros_1d = np.zeros(5)
print(zeros_1d)
zeros_2d = np.zeros((3,4))
print(zeros_2d)
#ones -> 1로 채우기 zeros -> 0으로 채우기

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [29]:
arr_1d = np.random.rand(5) # 0~1 사이 난수
print(arr_1d)
arr_2d = np.random.rand(2,2)
print(arr_2d)

[0.08005822 0.80675511 0.30050714 0.97811945 0.61256868]
[[0.30835333 0.06845962]
 [0.10984713 0.61917622]]


In [35]:
# Numpy LAB
arr1 = np.arange(1,10,2, dtype=int)
print(arr1)
arr2 = np.ones((3,4))
print(arr2)
arr3 = np.linspace(0,1,10)
print(arr3)

[1 3 5 7 9]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [56]:
#Numpy LAB
arr = np.arange(1,26)
arr = arr.reshape(5,5)
print(arr)
print(arr.shape)

print(arr[3,3])
print(arr[0:2,0:2])
print(arr[3:5, 3:5])
print(arr[:2, :]) 
print(arr[:, 3:5])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
(5, 5)
19
[[1 2]
 [6 7]]
[[19 20]
 [24 25]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]
 [24 25]]


In [58]:
#Numpy LAB
arr = np.arange(1,37)
arr = arr.reshape(3,3,4)
print(arr)
print(arr.shape, arr.size)
arr = arr.reshape(3,4,3)
print(arr)
arr = arr.flatten()
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]]
(3, 3, 4) 36
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]
